# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nextcloud Passwords' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nextcloud Passwords
  pod 'SwiftKeychainWrapper'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire'
  pod 'SQLite.swift', '~> 0.12.0'

end
